name: Issues
on:
    issues:
        types: [opened]
jobs:
    show-details:
        runs-on: ubuntu-latest
        steps:
            - name: Show issue details
              run: echo ${{ toJson(github.event) }}
